DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  fullname TEXT,
  email VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  create_datetime TIMESTAMP NOT NULL
);

